# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Regular version updates to 'develop' branch
  - package-ecosystem: "gradle"
    directory: "/"                    # Adjust if your project is in a subfolder
    schedule:
      interval: "weekly"
    target-branch: "develop"          # Send PRs to develop
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "com.squareup.okhttp3:*"
      - dependency-name: "org.hisp.dhis.mobile:designsystem"
      - dependency-name: "org.hisp.dhis:android-core"
    groups:
      gradle-updates:
        patterns:
          - "*"                       # Group all Gradle updates into one PR
        update-types:
          - "patch"                   # Only include patch updates (no major or minor versions)

  # GitHub Actions updates (optional)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 5
