[versions]
kotlinxDatetime = "0.7.1-0.6.x-compat" #Needs to be compatible with the Rule engine, update when it's updated
lifecycleRuntimeCompose = "2.9.5"
navigationCompose = "2.9.1"
sdk = "36"
minSdk = "21"
vCode = "151"
vName = "3.3.1"
gradle = "8.13.2"
kotlin = '2.2.21'
dagger = '2.57.2'
jacoco = '0.8.14'
designSystem = "0.6.1"
dhis2sdk = "1.13.1"
ruleEngine = "3.3.11"
expressionParser = "1.2.2"
appcompat = "1.7.1"
annotation = "1.9.1"
cardview = "1.0.0"
legacysupport = "1.0.0"
multidex = "2.0.1"
constraintlayout = "2.2.1"
lifecycle = "2.9.4"
work = "2.10.5"
exif = "1.4.2"
corektx = "1.17.0"
fragmentktx = "1.8.9"
recyclerview = "1.4.0"
compose = "1.9.3"
composePluginVersion = "1.9.1"
composePaging = "3.3.6"
pagingTesting = "3.3.6"
composeConstraintLayout = "1.1.1"
activityCompose = "1.11.0"
viewModelCompose = "2.9.4"
material = "1.13.0"
material3 = "1.4.0"
themeAdapter = "0.36.0"
pinlock = "2.1.0"
fancyshowcase = "1.4.0"
lottie = "6.6.10"
rxjava = "2.2.21"
rxandroid = "2.1.1"
maplibremarkerview = "3.0.2"
maplibreannotation = "3.0.2"
matomo = "4.4"
sentry = "8.29.0"
sentryPlugin = "5.12.2"
timber = "5.0.1"
rxlint = "1.7.8"
crashactivity = "2.4.0"
zxing = "3.5.4"
zxingandroid = "4.3.0"
root = "0.1.1"
openid = "0.11.1"
conscrypt = "2.5.3"
gson = "2.13.2"
okhttp = "4.12.0"
jodatime = "2.14.0"
glide = "5.0.5"
guava = "33.5.0-android"
mockito = "5.20.0"
mockito-kotlin = "6.1.0"
junit = "4.13.2"
mockito_inline = "5.2.0"
javafaker = "1.0.2"
junit_ext = "1.3.0"
espresso_core = "3.7.0"
androidx_test_orchestrator = "1.6.1"
androidx_test_runner = "1.7.0"
androidx_test = "1.7.0"
dexmaker-mockito-inline = "2.28.6"
hamcrest = "3.0"
kotlinxserialization = "1.9.0"
desugar_jdk_libs = "2.1.5"
google_truth = "1.4.5"
kotlinxcoroutines = "1.10.2"
rxrelay = "2.1.1"
preference_ktx = "1.2.1"
uiautomator = "2.3.0"
maplibre = "11.13.5"
maplibregeogson = "6.0.1"
material3WindowSize = "1.4.0"
material3WindowSizeCompose = "1.8.2"
material3AdaptiveAndroid = "1.1.0"
koin = "4.1.1"
junitJupiter = "6.0.1"
ktxml = "1.0.0"
atomicfu = "0.29.0"
playservicesauth = "21.4.0"
playservicesphone = "18.0.1" #Can not be updated to latest due minSDK requirement of 23
ksp = "2.2.20-2.0.4"
commonsText = "1.14.0"
ktlint = "13.1.0"
sonarqube = "7.0.0.6105"
browser = "1.9.0"
biometric = "1.1.0"
coil = "3.3.0"
cyclonedx = "2.1.0"

[libraries]
gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlinPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }
dhis2-android-sdk = { group = "org.hisp.dhis", name = "android-core", version.ref = "dhis2sdk" }
dhis2-ruleengine = { group = "org.hisp.dhis.rules", name = "rule-engine-jvm", version.ref = "ruleEngine" }
dhis2-expressionparser = { group = "org.hisp.dhis.lib.expression", name = "expression-parser-jvm", version.ref = "expressionParser" }
dhis2-mobile-designsystem = { group = "org.hisp.dhis.mobile", name = "designsystem", version.ref = "designSystem" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
androidx-activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentktx" }
androidx-viewModelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-compose = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }
androidx-compose-uitooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "composePaging" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
test-androidx-paging = { group = "androidx.paging", name = "paging-testing", version.ref = "pagingTesting" }
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "corektx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacysupport" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
androidx-workrx = { group = "androidx.work", name = "work-rxjava2", version.ref = "work" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exif" }
androidx-preferenceKtx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference_ktx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class-android", version.ref = "material3WindowSize" }
compose-material3-window = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "material3WindowSizeCompose" }
androidx-material3-adaptative-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version.ref = "material3AdaptiveAndroid" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxserialization" }
google-guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
google-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playservicesauth" }
google-auth-apiphone = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "playservicesphone" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-material3-themeadapter = { group = "com.google.accompanist", name = "accompanist-themeadapter-material3", version.ref = "themeAdapter" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
network-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
dates-jodatime = { group = "joda-time", name = "joda-time", version.ref = "jodatime" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
rx-java = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
rx-android = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxandroid" }
rx-relay = { group = "com.jakewharton.rxrelay2", name = "rxrelay", version.ref = "rxrelay" }
github-pinlock = { group = "com.github.aritraroy", name = "PinLockView", version.ref = "pinlock" }
github-fancyshowcase = { group = "com.github.faruktoptas", name = "FancyShowCaseView", version.ref = "fancyshowcase" }
github-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
github-glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
github-charts = { group = "com.github.PhilJay", name = "MPAndroidChart", version = "v3.1.0" }
barcodeScanner-zxing = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
barcodeScanner-zxing-android = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingandroid" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
analytics-matomo = { group = "com.github.matomo-org", name = "matomo-sdk-android", version.ref = "matomo" }
analytics-rxlint = { group = "nl.littlerobots.rxlint", name = "rxlint", version.ref = "rxlint" }
analytics-customactivityoncrash = { group = "cat.ereza", name = "customactivityoncrash", version.ref = "crashactivity" }
analytics-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
analytics-sentry = { group = "io.sentry", name = "sentry-android", version.ref = "sentry" }
analytics-sentry-compose = { group = "io.sentry", name = "sentry-compose-android", version.ref = "sentry" }
security-rootbeer = { group = "com.scottyab", name = "rootbeer-lib", version.ref = "root" }
security-openId = { group = "net.openid", name = "appauth", version.ref = "openid" }
security-conscrypt = { group = "org.conscrypt", name = "conscrypt-android", version.ref = "conscrypt" }
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-archCoreTesting = { group = "androidx.arch.core", name = "core-testing", version = "2.2.0" }
test-testCore = { group = "androidx.test", name = "core", version.ref = "androidx_test" }
test-mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
test-mockitoInline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito_inline" }
test-mockitoKotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
test-dexmaker-mockitoInline = { group = "com.linkedin.dexmaker", name = "dexmaker-mockito-inline", version.ref = "dexmaker-mockito-inline" }
test-truth = { group = "com.google.truth", name = "truth", version.ref = "google_truth" }
test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidx_test_orchestrator" }
test-testRunner = { group = "androidx.test", name = "runner", version.ref = "androidx_test_runner" }
test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_core" }
test-espresso-idlingresource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso_core" }
test-espresso-idlingconcurrent = { group = "androidx.test.espresso.idling", name = "idling-concurrent", version.ref = "espresso_core" }
test-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso_core" }
test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso_core" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx_test" }
test-junitKtx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit_ext" }
test-junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit_ext" }
test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
test-support-annotations = { group = "com.android.support", name = "support-annotations", version = "28.0.0" }
test-rx2-idler = { group = "com.squareup.rx.idler", name = "rx2-idler", version = "0.11.0" }
test-kotlinCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxcoroutines" }
test-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
test-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
test-compose-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "compose" }
test-hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
test-turbine = { group = "app.cash.turbine", name = "turbine", version = "1.2.1" }
test-javafaker = { group = "com.github.javafaker", name = "javafaker", version.ref = "javafaker" }
maps-maplibre = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre" }
maps-geojson = { group = "org.maplibre.gl", name = "android-sdk-geojson", version.ref = "maplibregeogson" }
maps-markerViewPlugin = { group = "org.maplibre.gl", name = "android-plugin-markerview-v9", version.ref = "maplibremarkerview" }
maps-annotationPlugin = { group = "org.maplibre.gl", name = "android-plugin-annotation-v9", version.ref = "maplibreannotation" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
ktxml = { module = "org.kobjects.ktxml:core", version.ref = "ktxml" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil"}
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil"}

[plugins]
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "kotlinx-serialization" }
compose = { id = "org.jetbrains.compose", version.ref = "composePluginVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
sentry = { id = "io.sentry.android.gradle", version.ref = "sentryPlugin" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }

[bundles]
uicomponents-implementation = ["androidx-coreKtx", "androidx-material3", "androidx-material3-window", "androidx-material3-adaptative-android", "google-material", "lottie-compose", "dhis2-mobile-designsystem"]
uicomponents-api = ["dhis2-mobile-designsystem", "androidx-compose-constraintlayout", "androidx-compose-preview", "androidx-compose-ui", "google-material3-themeadapter"]
uicomponents-debugapi = ["androidx-compose-uitooling"]
uicomponents-androidtest = ["test-junit-ext"]
analytics-implementation = ["androidx-cardview", "androidx-constraintlayout"]
analytics-api = ["github-charts"]
analytics-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-kotlinCoroutines", "test-archCoreTesting"]
form-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-testCore", "test-archCoreTesting", "test-kotlinCoroutines"]
map-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-turbine", "test-archCoreTesting", "test-kotlinCoroutines"]
table-implementation = ["kotlin-serialization-json", "androidx-appcompat", "androidx-activity-compose", "androidx-compose", "androidx-compose-constraintlayout", "androidx-compose-preview", "androidx-compose-ui", "androidx-compose-livedata"]
table-debugImplementation = ["androidx-compose-uitooling", "test-ui-test-manifest"]
table-test = ["test-junit"]
table-androidTest = ["test-compose-ui-test", "test-uiautomator", "test-junitKtx", "test-espresso"]
stock-implementation = ["androidx-activity-compose", "androidx-annotation", "rx-relay", "security-openId", "androidx-preferenceKtx", "androidx-work", "androidx-activityKtx", "androidx-lifecycle-viewmodel-compose", "analytics-customactivityoncrash"]
stock-core = ["desugar"]
stock-test = ["test-mockitoKotlin", "test-mockitoInline", "test-archCoreTesting", "test-javafaker", "test-kotlinCoroutines"]
tracker-implementation = ["androidx-lifecycle-viewmodel-compose", "androidx-activity-compose"]
tracker-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-testCore", "test-archCoreTesting", "test-kotlinCoroutines"]
