[versions]
kotlinxDatetime = "0.6.2"
sdk = "35"
minSdk = "21"
vCode = "143"
vName = "3.2.0"
gradle = "8.8.0"
kotlin = '2.0.21'
hilt = '2.47'
jacoco = '0.8.10'
designSystem = "0.5.0"
dhis2sdk = "1.12.0"
ruleEngine = "3.3.9"
expressionParser = "1.1.10"
appcompat = "1.6.1"
annotation = "1.6.0"
cardview = "1.0.0"
legacysupport = "1.0.0"
multidex = "2.0.1"
constraintlayout = "2.1.4"
lifecycle = "2.6.1"
work = "2.8.1"
exif = "1.3.6"
corektx = "1.10.1"
fragmentktx = "1.6.1"
dynamicanimation = "1.0.0"
viewpager2 = "1.0.0"
recyclerview = "1.3.1"
compose = "1.5.4"
composePlugin = "1.7.3"
composePaging = "3.3.0"
composeLifecycle = "2.8.1"
composeConstraintLayout = "1.0.1"
activityCompose = "1.8.2"
viewModelCompose = "2.7.0"
compose_ui_test = "1.5.4"
material = "1.9.0"
material3 = "1.1.1"
themeAdapter = "0.28.0"
pinlock = "2.1.0"
fancyshowcase = "1.3.9"
lottie = "6.1.0"
rxjava = "2.2.21"
rxandroid = "2.1.1"
rxbindings = "2.1.1"
autovalue = "1.6.6"
autovalueparcel = "0.2.7"
mapboxmarkerview = "0.3.0"
mapboxannotation = "0.8.0"
matomo = "4.1.2"
sentry = "7.14.0"
timber = "5.0.1"
rxlint = "1.6"
crashactivity = "2.3.0"
zxing = "3.5.0"
zxingbarcode = "1.9.8"
zxingandroid = "4.3.0"
root = "0.0.7"
openid = "0.8.1"
conscrypt = "2.5.2"
gson = "2.9.0"
okhttp = "4.9.3"
jodatime = "2.10.5"
glide = "4.9.0"
guava = "31.1-android"
mockito = "5.2.0"
mockito-kotlin = "5.1.0"
junit = "4.13.2"
mockito_inline = "5.2.0"
javafaker = "1.0.2"
junit_ext = "1.1.5"
espresso_core = "3.6.1"
androidx_test_orchestrator = "1.4.2"
androidx_test_runner = "1.5.2"
androidx_test = "1.5.0"
dexmaker-mockito-inline = "2.28.1"
hamcrest = "2.2"
kotlinxserialization = "1.5.1"
desugar_jdk_libs = "2.0.4"
google_truth = "1.1.2"
kotlinxcoroutines = "1.6.4"
rxrelay = "2.1.1"
preference_ktx = "1.2.1"
uiautomator = "2.2.0"
maplibre = "10.2.0"
material3WindowSize = "1.2.0"
material3WindowSizeCompose = "1.7.1"
material3AdaptiveAndroid = "1.0.0"
agp = "8.7.2"

uiTooling = "1.7.6"
koin = "4.0.2"
lifecycleViewmodel = "2.8.7"
androidx-navigation = "2.7.0"
junitJupiter = "5.8.1"
ktxml = "0.3.2"
atomicfu = "0.27.0"
[libraries]
gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlinPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
hiltPlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }
dhis2-android-sdk = { group = "org.hisp.dhis", name = "android-core", version.ref = "dhis2sdk" }
dhis2-ruleengine = { group = "org.hisp.dhis.rules", name = "rule-engine-jvm", version.ref = "ruleEngine" }
dhis2-expressionparser = { group = "org.hisp.dhis.lib.expression", name = "expression-parser-jvm", version.ref = "expressionParser" }
dhis2-mobile-designsystem = { group = "org.hisp.dhis.mobile", name = "designsystem", version.ref = "designSystem" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
androidx-activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentktx" }
androidx-viewModelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-compose = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }
androidx-compose-uitooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "compose" }
androidx-compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "composePaging" }
androidx-compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "corektx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacysupport" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
androidx-workrx = { group = "androidx.work", name = "work-rxjava2", version.ref = "work" }
androidx-workgcm = { group = "androidx.work", name = "work-gcm", version.ref = "work" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exif" }
androidx-preferenceKtx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference_ktx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class-android", version.ref = "material3WindowSize" }
compose-material3-window = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "material3WindowSizeCompose" }
androidx-material3-adaptative-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version.ref = "material3AdaptiveAndroid" }
androidx-dynamicanimation = { group = "androidx.dynamicanimation", name = "dynamicanimation", version.ref = "dynamicanimation" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version = "1.1.0" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxserialization" }
google-guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
google-auth = { group = "com.google.android.gms", name = "play-services-auth", version = "20.6.0" }
google-auth-apiphone = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version = "18.0.1" }
google-autoValue = { group = "com.google.auto.value", name = "auto-value", version.ref = "autovalue" } #TODO: this should be removed
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-material3-themeadapter = { group = "com.google.accompanist", name = "accompanist-themeadapter-material3", version.ref = "themeAdapter" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
network-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
dates-jodatime = { group = "joda-time", name = "joda-time", version.ref = "jodatime" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "hilt" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "hilt" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
rx-java = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
rx-android = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxandroid" }
rx-binding-compat = { group = "com.jakewharton.rxbinding2", name = "rxbinding-appcompat-v7", version.ref = "rxbindings" }
rx-relay = { group = "com.jakewharton.rxrelay2", name = "rxrelay", version.ref = "rxrelay" }
github-pinlock = { group = "com.github.aritraroy", name = "PinLockView", version.ref = "pinlock" }
github-fancyshowcase = { group = "com.github.faruktoptas", name = "FancyShowCaseView", version.ref = "fancyshowcase" }
github-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
github-glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
github-charts = { group = "com.github.PhilJay", name = "MPAndroidChart", version = "v3.1.0" }
github-treeView = { group = "com.github.bmelnychuk", name = "atv", version = "1.2.9" } #TODO: We should remove this
barcodeScanner-zxing = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
barcodeScanner-scanner = { group = "me.dm7.barcodescanner", name = "zxing", version.ref = "zxingbarcode" }
barcodeScanner-zxing-android = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingandroid" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
analytics-matomo = { group = "com.github.matomo-org", name = "matomo-sdk-android", version.ref = "matomo" }
analytics-rxlint = { group = "nl.littlerobots.rxlint", name = "rxlint", version.ref = "rxlint" }
analytics-customactivityoncrash = { group = "cat.ereza", name = "customactivityoncrash", version.ref = "crashactivity" }
analytics-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
analytics-sentry = { group = "io.sentry", name = "sentry-android", version.ref = "sentry" }
analytics-sentry-compose = { group = "io.sentry", name = "sentry-compose-android", version.ref = "sentry" }
security-rootbeer = { group = "com.scottyab", name = "rootbeer-lib", version.ref = "root" }
security-openId = { group = "net.openid", name = "appauth", version.ref = "openid" }
security-conscrypt = { group = "org.conscrypt", name = "conscrypt-android", version.ref = "conscrypt" }
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-archCoreTesting = { group = "androidx.arch.core", name = "core-testing", version = "2.2.0" }
test-testCore = { group = "androidx.test", name = "core", version.ref = "androidx_test" }
test-mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
test-mockitoInline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito_inline" }
test-mockitoKotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
test-dexmaker-mockitoInline = { group = "com.linkedin.dexmaker", name = "dexmaker-mockito-inline", version.ref = "dexmaker-mockito-inline" }
test-truth = { group = "com.google.truth", name = "truth", version.ref = "google_truth" }
test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidx_test_orchestrator" }
test-testRunner = { group = "androidx.test", name = "runner", version.ref = "androidx_test_runner" }
test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_core" }
test-espresso-idlingresource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso_core" }
test-espresso-idlingconcurrent = { group = "androidx.test.espresso.idling", name = "idling-concurrent", version.ref = "espresso_core" }
test-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso_core" }
test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso_core" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx_test" }
test-junitKtx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit_ext" }
test-junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit_ext" }
test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
test-support-annotations = { group = "com.android.support", name = "support-annotations", version = "28.0.0" }
test-rx2-idler = { group = "com.squareup.rx.idler", name = "rx2-idler", version = "0.11.0" }
test-kotlinCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxcoroutines" }
test-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose_ui_test" }
test-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose_ui_test" }
test-hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
test-turbine = { group = "app.cash.turbine", name = "turbine", version = "0.12.1" }
test-javafaker = { group = "com.github.javafaker", name = "javafaker", version.ref = "javafaker" }
maps-maplibre = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre" }
maps-geojson = { group = "org.maplibre.gl", name = "android-sdk-geojson", version = "5.9.0" }
maps-markerViewPlugin = { group = "com.mapbox.mapboxsdk", name = "mapbox-android-plugin-markerview-v8", version.ref = "mapboxmarkerview" }
maps-annotationPlugin = { group = "com.mapbox.mapboxsdk", name = "mapbox-android-plugin-annotation-v9", version.ref = "mapboxannotation" }
dispatcher-dispatchBOM = { group = "com.rickbusarow.dispatch", name = "dispatch-bom", version = "1.0.0-beta10" } #TODO: I don't know how or why we are using this
dispatcher-dispatchCore = { group = "com.rickbusarow.dispatch", name = "dispatch-core" }
dispatcher-dispatchEspresso = { group = "com.rickbusarow.dispatch", name = "dispatch-android-espresso", version = "1.0.0-beta10" }
deprecated-autoValueParcel = { group = "com.ryanharter.auto.value", name = "auto-value-parcel", version.ref = "autovalueparcel" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewmodel" }
androidx-lifecycle-viewmodel-compose-kpm = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodel" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
ktxml = { module = "org.kobjects.ktxml:core", version.ref = "ktxml" }
[plugins]
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
uicomponents-implementation = ["androidx-coreKtx", "androidx-material3", "androidx-material3-window", "androidx-material3-adaptative-android", "androidx-material3-adaptative-android", "google-material", "lottie-compose", "dhis2-mobile-designsystem"]
uicomponents-api = ["dhis2-mobile-designsystem", "androidx-compose-constraintlayout", "androidx-compose-preview", "androidx-compose-ui", "google-material3-themeadapter"]
uicomponents-debugapi = ["androidx-compose-uitooling"]
uicomponents-androidtest = ["test-junit-ext"]
analytics-implementation = ["androidx-cardview", "androidx-constraintlayout"]
analytics-api = ["github-charts"]
analytics-kapt = ["dagger-compiler"]
analytics-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-kotlinCoroutines", "test-archCoreTesting"]
form-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-testCore", "test-archCoreTesting", "test-kotlinCoroutines"]
map-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-turbine", "test-archCoreTesting", "test-kotlinCoroutines"]
table-implementation = ["kotlin-serialization-json", "androidx-appcompat", "androidx-activity-compose", "androidx-compose", "androidx-compose-constraintlayout", "androidx-compose-preview", "androidx-compose-ui", "androidx-compose-livedata"]
table-debugImplementation = ["androidx-compose-uitooling", "test-ui-test-manifest"]
table-test = ["test-junit"]
table-androidTest = ["test-compose-ui-test", "test-uiautomator", "test-junitKtx", "test-espresso"]
stock-implementation = ["androidx-activity-compose", "androidx-annotation", "rx-relay", "security-openId", "androidx-preferenceKtx", "androidx-work", "androidx-workgcm", "androidx-activityKtx", "androidx-lifecycle-viewmodel-compose", "analytics-customactivityoncrash", "dagger-hilt-android"]
stock-core = ["desugar"]
stock-kapt = ["dagger-hilt-compiler"]
stock-test = ["test-mockitoKotlin", "test-mockitoInline", "test-archCoreTesting", "test-javafaker", "test-kotlinCoroutines"]
tracker-implementation = ["androidx-lifecycle-viewmodel-compose", "androidx-activity-compose"]
tracker-test = ["test-mockitoCore", "test-mockitoInline", "test-mockitoKotlin", "test-testCore", "test-archCoreTesting", "test-kotlinCoroutines"]
